---
name: amnezia

services:
  awg:
    image: amnezia-awg
    container_name: amnezia-awg
    build:
      context: server_scripts/awg
      dockerfile: Dockerfile
    networks:
      - dns-net
    volumes:
      - /lib/modules:/lib/modules
      - ./amnezia-awg/:/opt/amnezia/
      - ./server_scripts/awg/:/scripts:ro
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    ports:
      - "${AWG_SERVER_PORT:-51820}:${AWG_SERVER_PORT:-51820}/udp"
    environment:
      SERVER_IP_ADDRESS: $SERVER_IP_ADDRESS
      AWG_SUBNET_IP: ${AWG_SUBNET_IP:-10.8.1.0}
      AWG_SUBNET_CIDR: ${AWG_SUBNET_CIDR:-24}
      AWG_SERVER_PORT: ${AWG_SERVER_PORT:-51820}
      JUNK_PACKET_COUNT: ${JUNK_PACKET_COUNT:-3}
      JUNK_PACKET_MIN_SIZE: ${JUNK_PACKET_MIN_SIZE:-10}
      JUNK_PACKET_MAX_SIZE: ${JUNK_PACKET_MAX_SIZE:-30}
      INIT_PACKET_JUNK_SIZE: ${INIT_PACKET_JUNK_SIZE:-15}
      RESPONSE_PACKET_JUNK_SIZE: ${RESPONSE_PACKET_JUNK_SIZE:-18}
      INIT_PACKET_MAGIC_HEADER: ${INIT_PACKET_MAGIC_HEADER:-1020325451}
      RESPONSE_PACKET_MAGIC_HEADER: ${RESPONSE_PACKET_MAGIC_HEADER:-3288052141}
      UNDERLOAD_PACKET_MAGIC_HEADER: ${UNDERLOAD_PACKET_MAGIC_HEADER:-1766607858}
      TRANSPORT_PACKET_MAGIC_HEADER: ${TRANSPORT_PACKET_MAGIC_HEADER:-2528465083}
    entrypoint: /bin/bash
    command: -c  "./scripts/configure_container.sh && dumb-init /scripts/start.sh"

  wireguard:
    image: amnezia-wireguard
    container_name: amnezia-wireguard
    build:
      context: server_scripts/wireguard
      dockerfile: Dockerfile
    networks:
      - dns-net
    volumes:
      - /lib/modules:/lib/modules
      - ./amnezia-wireguard/:/opt/amnezia/
      - ./server_scripts/wireguard/:/scripts:ro
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    ports:
      - "${WIREGUARD_SERVER_PORT:-51820}:${WIREGUARD_SERVER_PORT:-51820}/udp"
    environment:
      SERVER_IP_ADDRESS: $SERVER_IP_ADDRESS
      WIREGUARD_SUBNET_IP: ${WIREGUARD_SUBNET_IP:-10.8.1.0}
      WIREGUARD_SUBNET_CIDR: ${WIREGUARD_SUBNET_CIDR:-24}
      WIREGUARD_SERVER_PORT: ${WIREGUARD_SERVER_PORT:-51820}
    entrypoint: /bin/bash
    command: -c  "./scripts/configure_container.sh && dumb-init /scripts/start.sh"

  dns:
    image: adguard/adguardhome:v0.107.60
    container_name: amnezia-dns
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - "./amnezia-dns/:/opt/adguardhome"
      - "./caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DOMAIN}:/certs:ro"
    networks:
      dns-net:
        ipv4_address: 172.29.172.254
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.9.1
    container_name: amnezia-caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Berlin}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
      - DOMAIN=$DOMAIN
      - DNS_QUERY_TOKEN=${DNS_QUERY_TOKEN:-}
    ports:
      - "80:80"
      - "443:443"
      - "853:853"  # Порт для DoT
      - "853:853/udp"  # Порт для DoT
    volumes:
      - ./server_scripts/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      dns-net:


networks:
  dns-net:
    ipam:
      config:
        - subnet: 172.29.172.0/24
      options:
        com.docker.network.bridge.name: amn0